const { Product, ProductImage } = require("../models");
const { Op } = require("sequelize");


exports.handleAddProduct = async (req, res) => {
  const { productName, productPrice, productDescription } = req.body;

  try {
    const existingProduct = await Product.findOne({
      where: {
        name: productName,
      },
    });

    if (existingProduct) {
      return res.status(404).json({
        ok: false,
        msg: "Product already exists",
      });
    }

    // Create the product
    const product = await Product.create({
      name: productName,
      price: productPrice,
      description: productDescription,
    });

    // Handle multiple images
    const images = req.files; // Assuming you use 'files' for multiple file uploads

    if (!images) {
      return res.status(400).json({
        ok: false,
        msg: "No images uploaded",
      });
    }

    // Prepare the array of objects to be inserted
    const imageObjects = images.map(image => {
      return {
        productId: product.id,
        imageUrl: image.filename, // Using the filename generated by Multer
      };
    });

    // Use bulkCreate to insert multiple records at once
    const productImages = await ProductImage.bulkCreate(imageObjects);

    return res.status(200).json({
      ok: true,
      msg: "Product and images added successfully",
      product: product,
      images: productImages,
    });
  } catch (error) {
    console.error(error);
    return res.status(500).json({
      ok: false,
      msg: "Internal server error",
    });
  }
};
